<?xml version="1.0" encoding="utf-8"?><Database Name="MarvelDB" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ITCOMP\TEST;Initial Catalog=MarvelDB;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="MarvelDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryProperty" Member="CategoryProperties" ThisKey="CategoryID" OtherKey="CategoriesID" Type="CategoryProperty" />
      <Association Name="Category_ProductsRefCategory" Member="ProductsRefCategories" ThisKey="CategoryID" OtherKey="CategoryID" Type="ProductsRefCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserRoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserRightID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserID" OtherKey="UserID" Type="Order" />
      <Association Name="User_UserProperty" Member="UserProperties" ThisKey="UserID" OtherKey="UserID" Type="UserProperty" />
      <Association Name="UserRight_User" Member="UserRight" ThisKey="UserRightID" OtherKey="UserRightID" Type="UserRight" IsForeignKey="true" />
      <Association Name="UserRole_User" Member="UserRole" ThisKey="UserRoleID" OtherKey="UserRolesID" Type="UserRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryProperties" Member="CategoryProperties">
    <Type Name="CategoryProperty">
      <Column Name="CategoriesPropertyID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoriesID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PropertName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryProperty" Member="Category" ThisKey="CategoriesID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryTypes" Member="DeliveryTypes">
    <Type Name="DeliveryType">
      <Column Name="DeliveryTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeliveryType" Member="DeliveryType1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DeliveryType_Order" Member="Orders" ThisKey="DeliveryTypeID" OtherKey="DeliveryTypeID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Languages" Member="Languages">
    <Type Name="Language">
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NewsDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsBody" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPaid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TotalSum" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrdersRefProduct" Member="OrdersRefProducts" ThisKey="OrderID" OtherKey="OrderID" Type="OrdersRefProduct" />
      <Association Name="DeliveryType_Order" Member="DeliveryType" ThisKey="DeliveryTypeID" OtherKey="DeliveryTypeID" Type="DeliveryType" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="OrderStatuse_Order" Member="OrderStatuse" ThisKey="OrderStatusID" OtherKey="OrderStatusID" Type="OrderStatuse" IsForeignKey="true" />
      <Association Name="PaymentType_Order" Member="PaymentType" ThisKey="PaymentTypeID" OtherKey="PaymentTypeID" Type="PaymentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersRefProducts" Member="OrdersRefProducts">
    <Type Name="OrdersRefProduct">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProductAndProperyRefID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrdersRefProduct" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrdersRefProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatuses" Member="OrderStatuses">
    <Type Name="OrderStatuse">
      <Column Name="OrderStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderStatus" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="OrderStatuse_Order" Member="Orders" ThisKey="OrderStatusID" OtherKey="OrderStatusID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageURL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PageBody" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentTypes" Member="PaymentTypes">
    <Type Name="PaymentType">
      <Column Name="PaymentTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentType" Member="PaymentType1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PaymentType_Order" Member="Orders" ThisKey="PaymentTypeID" OtherKey="PaymentTypeID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.ProductProperties" Member="ProductProperties">
    <Type Name="ProductProperty">
      <Column Name="PropertyID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsImportant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ProductProperty_ProductsRefPropery" Member="ProductsRefProperies" ThisKey="PropertyID" OtherKey="ProductPropertiesID" Type="ProductsRefPropery" />
      <Association Name="Product_ProductProperty" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="InStock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_OrdersRefProduct" Member="OrdersRefProducts" ThisKey="ProductID" OtherKey="ProductID" Type="OrdersRefProduct" />
      <Association Name="Product_ProductProperty" Member="ProductProperties" ThisKey="ProductID" OtherKey="ProductID" Type="ProductProperty" />
      <Association Name="Product_ProductsRefCategory" Member="ProductsRefCategories" ThisKey="ProductID" OtherKey="ProductID" Type="ProductsRefCategory" />
      <Association Name="Product_ProductsRefPropery" Member="ProductsRefProperies" ThisKey="ProductID" OtherKey="ProductID" Type="ProductsRefPropery" />
      <Association Name="Product_Stock" Member="Stocks" ThisKey="ProductID" OtherKey="ProductID" Type="Stock" />
      <Association Name="ProductType_Product" Member="ProductType" ThisKey="ProductTypeID" OtherKey="ProdcutTypeID" Type="ProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsRefCategories" Member="ProductsRefCategories">
    <Type Name="ProductsRefCategory">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_ProductsRefCategory" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Product_ProductsRefCategory" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsRefProperies" Member="ProductsRefProperies">
    <Type Name="ProductsRefPropery">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductPropertiesID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ProductProperty_ProductsRefPropery" Member="ProductProperty" ThisKey="ProductPropertiesID" OtherKey="PropertyID" Type="ProductProperty" IsForeignKey="true" />
      <Association Name="Product_ProductsRefPropery" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTypes" Member="ProductTypes">
    <Type Name="ProductType">
      <Column Name="ProdcutTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductType" Member="ProductType1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ProductType_Product" Member="Products" ThisKey="ProdcutTypeID" OtherKey="ProductTypeID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="StockItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Stock" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProperties" Member="UserProperties">
    <Type Name="UserProperty">
      <Column Name="UsersPropertyID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserProperyKey" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserProperyValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserProperty" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRights" Member="UserRights">
    <Type Name="UserRight">
      <Column Name="UserRightID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserRightText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="UserRight_User" Member="Users" ThisKey="UserRightID" OtherKey="UserRightID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRolesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserRolesName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserRoleRights" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserRole_User" Member="Users" ThisKey="UserRolesID" OtherKey="UserRoleID" Type="User" />
    </Type>
  </Table>
</Database>